version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: long-task-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
